### ISSUE TITLE
corrplot todo lists

### ISSUE THREAD

**Issue by cokelaer** [biokit/biokit#6]
- [x] colorbar range is not linear and tick labels foes from -1 to 0 : seems to work now
- [ ] addrect option is missing : wont fix
- [ ] ability to cross values below or above some threshold: wont'add . Using clip() on the dataframe solve that issue.
- [ ] check arguments
- [x] doc
- [x] tests
